<?php


namespace Aufgecodet\FFA;


use Aufgecodet\FFA\listener\BasicListener;
use pocketmine\item\VanillaItems;
use pocketmine\player\Player;
use pocketmine\plugin\PluginBase;
use pocketmine\Server;
use pocketmine\utils\Config;
use raklib\generic\ReceiveReliabilityLayer;

class Main extends PluginBase{
    /**
     * @return void
     */
     public function registerAll():void{
           $this->getServer()->getPluginManager()->registerEvents(new BasicListener($this),$this);
           $this->getConfig()->save();

     }
    public static function getInstance():self{
        return  self::$instance;
    }
    /** @var $this */
    public static $instance;
    /**
     * @return void
     */
    public function onEnable(): void
    {
        self::$instance = $this;
        $this->registerAll();
    }

    /**
     * @return Config
     */
    public function getConfig(): Config
    {
        return parent::getConfig(); // TODO: Change the autogenerated stub
    }

    /**
     * @param Player $player
     * @return void
     */
    public function giveItems(Player $player){
          $player->getInventory()->clearAll();
          $player->getArmorInventory()->clearAll();
          $sword = VanillaItems::IRON_SWORD();
          $apple = VanillaItems::GOLDEN_APPLE();
          $bow = VanillaItems::BOW();
          $arrow = VanillaItems::ARROW();

          $chestplate = VanillaItems::IRON_CHESTPLATE();
          $boots = VanillaItems::IRON_BOOTS();
          $helmet = VanillaItems::IRON_HELMET();
          $leggings = VanillaItems::IRON_LEGGINGS();

          $apple->setCount(4);
          $arrow->setCount(8);
          $player->getInventory()->addItem($sword);
        $player->getInventory()->addItem($apple);
        $player->getInventory()->addItem($bow);
        $player->getInventory()->addItem($arrow);
        $player->getArmorInventory()->setBoots($boots);
        $player->getArmorInventory()->setChestplate($chestplate);
        $player->getArmorInventory()->setHelmet($helmet);
        $player->getArmorInventory()->setLeggings($leggings);

    }

    /**
     * @param Player $player
     * @return void
     */
    public function teleport(Player $player){
        Server::getInstance()->getWorldManager()->loadWorld($this->getConfig()->get("map"));
        $player->teleport(Server::getInstance()->getWorldManager()->getWorldByName($this->getConfig()->get("map"))->getSafeSpawn());
    }
}